server:
    port: 8001
spring:
    profiles:
        active: prov
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.jimu.social.interfaces.domain

logging:
    config: classpath:log.xml
    level:
        com.lucifer.springboot.cache.mapper: debug